import type { EcaRule } from './types';

function rule(
  id: string,
  name: string,
  description: string,
  event: EcaRule['event'],
  conditions: EcaRule['conditions'],
  actions: EcaRule['actions'],
  enabled = true,
): EcaRule {
  const now = new Date().toISOString();
  return {
    id,
    name,
    description,
    event,
    conditions,
    actions,
    enabled,
    ownerId: 'system',
    history: [],
    createdAt: now,
    updatedAt: now,
  };
}

export const ECA_PRESET_RULES: EcaRule[] = [
  rule(
    'r-001',
    'TKGM ipotekli → review flag',
    'TKGM kaydında ipotek bulunan ilanlar moderasyona düşer.',
    'listing.created',
    [{ field: 'listing.tkgmStatus', op: 'eq', value: 'ipotekli' }],
    [
      { type: 'flag.review', params: { reason: 'tkgm:ipotekli' } },
      { type: 'notify.role', params: { role: 'admin', priority: 'soon' } },
    ],
  ),
  rule(
    'r-002',
    'Draft 7+ gün → satıcıya hatırlat',
    'Bir haftadır taslakta bekleyen ilanlar için satıcıya AI özet hatırlatması.',
    'system.cron.daily',
    [{ field: 'daysInDraft', op: 'gte', value: 7 }],
    [{ type: 'notify.user', params: { template: 'draft.reminder', priority: 'later' } }],
  ),
  rule(
    'r-003',
    'Fiyat %20+ değişim → anomali etiketi',
    'Fiyatın %20 üzeri/altı değişmesi durumunda anomali etiketi eklenir.',
    'listing.price_changed',
    [{ field: 'changeRatio', op: 'gte', value: 0.2 }],
    [
      { type: 'tag.add', params: { tag: 'fiyat-anomali' } },
      { type: 'notify.role', params: { role: 'admin' } },
    ],
  ),
  rule(
    'r-004',
    'Teklif ≥%90 → satıcıya kabul önerisi',
    'Liste fiyatına yakın teklifler için tek tıkla kabul önerisi.',
    'offer.received',
    [{ field: 'offerRatio', op: 'gte', value: 0.9 }],
    [{ type: 'notify.user', params: { template: 'offer.accept-suggest' } }],
  ),
  rule(
    'r-005',
    'Mesaj 24h yanıtsız → AI draft',
    '24 saattir yanıtlanmayan mesajlar için satıcıya öneri taslağı.',
    'message.received',
    [{ field: 'silentHours', op: 'gte', value: 24 }],
    [{ type: 'ai.summarize', params: { kind: 'reply.draft' } }],
  ),
  rule(
    'r-006',
    'KYC 48h pending → hatırlatma',
    'KYC süreci 48 saattir tamamlanmamış kullanıcılara hatırlatma.',
    'user.kyc_status_changed',
    [{ field: 'pendingHours', op: 'gte', value: 48 }],
    [{ type: 'email.mock', params: { template: 'kyc.remind' } }],
  ),
  rule(
    'r-007',
    'Görüntülenme 24h ≥3 → popüler',
    'Günde 3+ görüntülenen ilanlara popüler etiketi.',
    'listing.viewed',
    [{ field: 'views24h', op: 'gte', value: 3 }],
    [{ type: 'tag.add', params: { tag: 'popüler' } }],
  ),
  rule(
    'r-008',
    'Aynı kullanıcı 5+ görüntüleme → sıcak alıcı',
    'Aynı ilanı 5 kez gören kullanıcı için sıcak alıcı etiketi.',
    'listing.viewed',
    [{ field: 'sameUserViews', op: 'gte', value: 5 }],
    [{ type: 'tag.add', params: { tag: 'sıcak-alıcı' } }],
  ),
  rule(
    'r-009',
    'TKGM şerh değişti → favorileyenlere uyarı',
    'Favorilemiş kullanıcılar TKGM durumu değişince bilgilendirilir.',
    'tkgm.flag_changed',
    [],
    [{ type: 'notify.user', params: { template: 'tkgm.flag', priority: 'now' } }],
  ),
  rule(
    'r-010',
    'Yayın bitimi 7 gün → yenileme',
    'Yayın süresi 7 gün kalan ilanlar için yenileme önerisi.',
    'system.cron.daily',
    [{ field: 'daysToExpiry', op: 'lte', value: 7 }],
    [{ type: 'email.mock', params: { template: 'listing.renew' } }],
  ),
  rule(
    'r-011',
    'Yeni satıcı → onboarding',
    'İlk kez kayıt olan satıcı kullanıcılara onboarding rehberi.',
    'user.signed_up',
    [{ field: 'role', op: 'eq', value: 'seller' }],
    [{ type: 'notify.user', params: { template: 'onboarding.seller' } }],
  ),
  rule(
    'r-012',
    'Hisseli tapu → risk uyarısı',
    'Hisseli tapulu ilanlar için alıcıya risk uyarısı.',
    'listing.created',
    [{ field: 'listing.tapuType', op: 'eq', value: 'hisseli' }],
    [{ type: 'tag.add', params: { tag: 'hisseli-risk' } }],
  ),
  rule(
    'r-013',
    'Fiyat alarmı abonesi → bildirim',
    'Abonenin filtresine uyan yeni ilanlarda bildirim.',
    'listing.created',
    [],
    [{ type: 'notify.user', params: { template: 'saved-search.match' } }],
  ),
  rule(
    'r-014',
    'Görsel eksik → yükleme hatırlat',
    '3 görselden az olan ilanlar için satıcıya hatırlatma.',
    'listing.updated',
    [{ field: 'imageCount', op: 'lt', value: 3 }],
    [{ type: 'notify.user', params: { template: 'listing.images-missing' } }],
  ),
  rule(
    'r-015',
    'Spam mesaj kalıbı → moderasyon',
    'Spam paterni taşıyan mesajlar moderasyona düşer.',
    'message.received',
    [{ field: 'body', op: 'regex', value: '(?i)kazanç|çek listenize|whatsapp \\+9' }],
    [{ type: 'flag.review', params: { reason: 'spam' } }],
  ),
  rule(
    'r-016',
    'Yüksek risk ilan → moderasyon',
    'AI risk skoru 70+ olan ilanlar yönetici incelemesine düşer.',
    'listing.created',
    [{ field: 'listing.aiRiskScore', op: 'gte', value: 70 }],
    [{ type: 'flag.review', params: { reason: 'high-risk' } }],
  ),
  rule(
    'r-017',
    'İlk mesaj → AI taslak yanıt',
    'Bir thread içindeki ilk mesaja AI taslak yanıt önerisi.',
    'message.received',
    [{ field: 'isFirst', op: 'eq', value: true }],
    [{ type: 'ai.summarize', params: { kind: 'first.reply' } }],
  ),
  rule(
    'r-018',
    'Premium alıcı → VIP öneri',
    'Yüksek vipScore alıcılara seçili ilan önerileri.',
    'system.cron.daily',
    [{ field: 'user.vipScore', op: 'gte', value: 80 }],
    [{ type: 'notify.user', params: { template: 'vip.weekly' } }],
  ),
  rule(
    'r-019',
    'Deniz manzaralı → manzara abonesi uyar',
    'Manzaralı arsa abonesi olan kullanıcılara bildirim.',
    'listing.created',
    [{ field: 'listing.features', op: 'contains', value: 'Deniz manzaralı' }],
    [{ type: 'notify.user', params: { template: 'sea-view' } }],
  ),
  rule(
    'r-020',
    'Çok teklif alan → yönetici eskalasyonu',
    '24 saatte 10+ teklif alan ilanlar yöneticiye iletilir.',
    'offer.received',
    [{ field: 'offers24h', op: 'gte', value: 10 }],
    [{ type: 'notify.role', params: { role: 'admin', priority: 'soon' } }],
  ),
  rule(
    'r-021',
    'Tarım/zeytinlik → otomatik etiket',
    'İmar türüne göre otomatik etiket.',
    'listing.created',
    [{ field: 'listing.imarType', op: 'in', value: ['tarim', 'zeytinlik'] }],
    [{ type: 'tag.add', params: { tag: 'tarımsal' } }],
  ),
  rule(
    'r-022',
    'Tekrarlanan red → moderasyon uyarısı',
    'Aynı satıcının 3+ ilanı reddedilmişse moderasyon uyarısı.',
    'listing.status_changed',
    [
      { field: 'newStatus', op: 'eq', value: 'rejected' },
      { field: 'sellerRejectCount', op: 'gte', value: 3 },
    ],
    [{ type: 'notify.role', params: { role: 'admin' } }],
  ),
  rule(
    'r-023',
    'Bozuk görsel → flag + mail',
    'Bozuk/erişilemez görsele sahip ilanlar için flag ve satıcıya mail.',
    'listing.updated',
    [{ field: 'brokenImageCount', op: 'gt', value: 0 }],
    [
      { type: 'flag.review', params: { reason: 'broken-image' } },
      { type: 'email.mock', params: { template: 'image.broken' } },
    ],
  ),
  rule(
    'r-024',
    'Günlük cron → özet rapor',
    'Her gün admin ekibine özet rapor.',
    'system.cron.daily',
    [],
    [{ type: 'email.mock', params: { template: 'daily.digest', to: 'admin' } }],
    false,
  ),
];
