/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List listings */
        get: operations["listListings"];
        put?: never;
        /** Create listing */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get listing detail */
        get: operations["getListing"];
        put?: never;
        post?: never;
        /** Delete listing (soft) */
        delete: operations["deleteListing"];
        options?: never;
        head?: never;
        /** Update listing (partial) */
        patch: operations["updateListing"];
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["listCustomers"];
        put?: never;
        /** Create customer */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get customer detail */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        /** Delete customer */
        delete: operations["deleteCustomer"];
        options?: never;
        head?: never;
        /** Update customer (partial) */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deals */
        get: operations["listDeals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move deal to a different pipeline stage */
        post: operations["moveDealStage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Buyer or staff login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout — adds the bearer token's jti to the revocation list
         * @description Wave-19 / A91 — Faz 12.8.c. If the request carries a valid Bearer token
         *     with a `jti` claim, that jti is added to an in-memory revocation set.
         *     Subsequent requests reusing the same token via /auth/me, /auth/refresh
         *     or any scope-gated `/api/v1/*` endpoint will receive 401 with
         *     `details.reason = "revoked"`. The revocation set is process-local and
         *     resets on restart — production must back this with Redis/DB.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user (from Bearer token)
         * @description Returns the `User` for the JWT subject. Rejects (401) when:
         *     - Authorization header missing/malformed
         *     - token signature invalid (`details.reason = "bad-signature"`)
         *     - token expired (`details.reason = "expired"`)
         *     - token's `jti` is in the revocation set (Wave-19 / A91,
         *       `details.reason = "revoked"`)
         *     - token subject no longer exists in the user store
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/offices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public offices */
        get: operations["listPublicOffices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/offices/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Public office profile */
        get: operations["getPublicOffice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public regions */
        get: operations["listPublicRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenants (super-admin) */
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit log entries */
        get: operations["listAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendar events */
        get: operations["listCalendarEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get calendar event detail */
        get: operations["getCalendarEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations (slim — no embedded messages) */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get conversation thread (with embedded messages) */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team performance leaderboard */
        get: operations["getReportsTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly close (count + revenue per month) */
        get: operations["getReportsMonthlyClose"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/customer-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer acquisition sources breakdown */
        get: operations["getReportsCustomerSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a near-expiry token for a fresh one
         * @description Refresh policy (apps/api/src/routes/auth.ts — Wave-16 / A77):
         *     - eligible only when `exp - now <= 5min`
         *     - absolute cap: `now - iat <= 24h` (no infinite refresh chains)
         *     - rejected if token's `jti` is in the revocation set
         *       (`details.reason = "revoked"`, Wave-19 / A91)
         *     The fresh token carries a new `jti` so a logout of the old one does
         *     not invalidate the refresh.
         */
        post: operations["refreshAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List finance transactions */
        get: operations["listFinanceTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cashflow inflow/outflow per period */
        get: operations["getFinanceCashflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finance KPIs (totals + forecast) */
        get: operations["getFinanceKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/pending-by-age": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aging buckets for pending receivables */
        get: operations["getFinancePendingByAge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/status-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts per status (Aktif / Pasif / Taslak)
         * @description Returns post-mutation counts derived from the in-memory listings
         *     state. Mirrored on the frontend by
         *     `packages/data/src/query/listings.ts → useListingStatusCounts`.
         */
        get: operations["getListingStatusCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/segment-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts per segment (Sıcak / Ilık / Soğuk)
         * @description Returns post-mutation counts derived from the in-memory customers
         *     state. Mirrored on the frontend by
         *     `packages/data/src/query/customers.ts → useCustomerSegmentCounts`.
         */
        get: operations["getCustomerSegmentCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListMeta: {
            total: number;
            nextCursor?: string | null;
            pageSize?: number;
        };
        Error: {
            error: {
                /**
                 * @example INVALID_INPUT
                 * @example NOT_FOUND
                 * @example UNAUTHORIZED
                 * @example PERMISSION_DENIED
                 * @example RATE_LIMITED
                 */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        CalendarEventType: "visit" | "deed" | "task" | "meeting" | "reminder";
        CalendarEvent: {
            /** @example E-9201 */
            id: string;
            type: components["schemas"]["CalendarEventType"];
            title: string;
            /**
             * Format: date-time
             * @description ISO start instant
             */
            date: string;
            /** @description Display-only HH:MM (Europe/Istanbul); derive from `date` when absent */
            time?: string;
            durationMin?: number;
            owner: string;
            location?: string;
            dealId?: string;
            customerName?: string;
            notes?: string;
        };
        /** @enum {string} */
        MessageChannel: "whatsapp" | "sahibinden" | "phone" | "email" | "internal";
        /** @enum {string} */
        MessageSender: "me" | "them" | "system";
        Message: {
            /** @example msg-001 */
            id: string;
            sender: components["schemas"]["MessageSender"];
            content: string;
            /** Format: date-time */
            time: string;
            channel?: components["schemas"]["MessageChannel"];
            attachments?: number;
        };
        ConversationSummary: {
            /** @example C-7401 */
            id: string;
            customerId: string;
            customerName: string;
            customerAvatarInitials: string;
            channel: components["schemas"]["MessageChannel"];
            lastPreview: string;
            /** Format: date-time */
            lastAt: string;
            unreadCount: number;
            pinned?: boolean;
            segment: components["schemas"]["CustomerSegment"];
        };
        Conversation: components["schemas"]["ConversationSummary"] & {
            messages: components["schemas"]["Message"][];
        };
        TeamRow: {
            owner: string;
            closed: number;
            active: number;
            /** @description TL */
            revenue: number;
            /** @description 0..1 fraction */
            conversion: number;
            avgResponseMin: number;
        };
        MonthlyClose: {
            /**
             * @description TR short month label, e.g. Kas, Ara, Oca
             * @example Nis
             */
            month: string;
            count: number;
            /** @description TL */
            revenue: number;
        };
        SourceRow: {
            /**
             * @description Lead acquisition channel name
             * @example Sahibinden
             * @example Referans
             * @example Hürriyet Emlak
             * @example Sosyal Medya
             * @example Walk-in
             */
            source: string;
            count: number;
            conversion: number;
        };
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /** @default false */
            rememberMe: boolean;
        };
        /**
         * @description Shared envelope returned by /auth/login and /auth/refresh.
         *     `token` is an HS256 JWT carrying claims:
         *       - sub: User.id
         *       - email: User.email
         *       - scopes: string[]
         *       - iat: unix-seconds issuance time
         *       - exp: unix-seconds expiry (iat + 3600 by default)
         *       - jti: UUID v4 — opaque token id, used by the revocation list
         *         (Wave-19 / A91). Old tokens without `jti` remain accepted for
         *         backward compatibility, but cannot be revoked individually.
         */
        AuthSessionEnvelope: {
            user: components["schemas"]["User"];
            /** @description HS256 JWT (`header.payload.signature`). */
            token: string;
            /**
             * Format: date-time
             * @description ISO-8601 of the token's `exp` (informational).
             */
            expiresAt: string;
        };
        AuthLoginResponse: components["schemas"]["AuthSessionEnvelope"];
        AuthRefreshResponse: components["schemas"]["AuthSessionEnvelope"];
        AuthMeResponse: {
            data: components["schemas"]["User"];
        };
        /** @enum {string} */
        ListingStatus: "Aktif" | "Pasif" | "Taslak";
        /** @enum {string} */
        ListingType: "İmarlı" | "Tarla" | "Zeytinlik" | "Villa Arsası";
        Listing: {
            /** @example 28.AY.0142 */
            id: string;
            title: string;
            city: string;
            district: string;
            type: components["schemas"]["ListingType"];
            /** @description m² */
            size: number;
            /** @description TL */
            price: number;
            status: components["schemas"]["ListingStatus"];
            views: number;
            weeklyTrend: number[];
            /** Format: date-time */
            lastUpdate: string;
            tags: string[];
            lat?: number | null;
            lng?: number | null;
        };
        ListingCreateInput: {
            title: string;
            city: string;
            district: string;
            type: components["schemas"]["ListingType"];
            size: number;
            price: number;
            status?: components["schemas"]["ListingStatus"];
            tags?: string[];
            lat?: number | null;
            lng?: number | null;
        };
        ListingPatchInput: {
            title?: string;
            price?: number;
            status?: components["schemas"]["ListingStatus"];
            tags?: string[];
        };
        /** @enum {string} */
        CustomerSegment: "Sıcak" | "Ilık" | "Soğuk";
        /** @enum {string} */
        CustomerStage: "İlk temas" | "Görüşme" | "Teklif" | "Kaparo" | "Tapu";
        Customer: {
            id: string;
            name: string;
            segment: components["schemas"]["CustomerSegment"];
            stage: components["schemas"]["CustomerStage"];
            /** Format: date-time */
            lastContact: string;
            value: number;
            /** @enum {string} */
            source: "Sahibinden" | "Hürriyet Emlak" | "Referans" | "Sosyal Medya" | "Walk-in";
            owner: string;
            interestArea: string;
            notes?: string | null;
        };
        /** @enum {string} */
        DealStatus: "Aktif" | "Bekliyor" | "Risk";
        Deal: {
            id: string;
            customerId: string;
            listingId: string;
            stage: components["schemas"]["CustomerStage"];
            status: components["schemas"]["DealStatus"];
            value: number;
            daysInStage: number;
            commissionPct?: number;
            notes?: string | null;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "tenant-admin" | "tenant-member" | "buyer" | "super-admin" | "support" | "compliance" | "readonly-auditor";
            tenantId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Office: {
            id: string;
            slug: string;
            name: string;
            city: string;
            district: string;
            description: string;
            founded: number;
            agentCount: number;
            listingCount: number;
            rating: number;
            reviewCount: number;
            phone?: string;
            /** Format: email */
            email?: string;
            whatsapp?: string;
            address?: string;
            hours?: string;
            specialties?: string[];
        };
        Region: {
            slug: string;
            name: string;
            city: string;
            description: string;
            marketStats: {
                avgPricePerSqm: number;
                activeBuyers: number;
                avgDealDays: number;
                yoy: string;
            };
            highlights: string[];
        };
        Tenant: {
            id: string;
            name: string;
            city: string;
            /** @enum {string} */
            plan: "Free" | "Pro" | "Enterprise";
            mrr: number;
            listingCount: number;
            userCount: number;
            /** Format: date-time */
            lastActiveAt: string;
            /** @enum {string} */
            status: "Aktif" | "Trial" | "Askıda" | "Churned";
            /** Format: date-time */
            createdAt: string;
        };
        AuditEntry: {
            id: string;
            actor: string;
            action: string;
            resourceType: string;
            resourceId: string;
            tenantId?: string | null;
            ip: string;
            userAgent: string;
            /** @enum {string} */
            outcome: "success" | "failure";
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            at: string;
        };
        /** @enum {string} */
        FinanceTransactionKind: "income" | "expense";
        /** @enum {string} */
        FinanceTransactionStatus: "Tamamlandı" | "Bekliyor" | "Gecikmiş";
        /** @enum {string} */
        FinanceTransactionCategory: "Tahsilat" | "Komisyon" | "Gider" | "Vergi";
        FinanceTransaction: {
            id: string;
            /** Format: date-time */
            date: string;
            amount: number;
            /**
             * @default TRY
             * @enum {string}
             */
            currency: "TRY" | "USD" | "EUR";
            kind: components["schemas"]["FinanceTransactionKind"];
            category: components["schemas"]["FinanceTransactionCategory"];
            status: components["schemas"]["FinanceTransactionStatus"];
            customerId?: string | null;
            dealId?: string | null;
            party?: string | null;
            description?: string | null;
            daysOverdue?: number | null;
        };
        FinanceCashflowPoint: {
            /** @description YYYY-MM or short month label */
            period: string;
            inflow: number;
            outflow: number;
            net?: number;
        };
        FinanceKPI: {
            total: number;
            avg: number;
            /** @description signed % delta vs previous month */
            lastMonthDelta: number;
            /** @description projected next-month net */
            forecast: number;
            tahsilatBuMonth?: number;
            komisyonBuMonth?: number;
            giderBuMonth?: number;
            bekleyen?: number;
        };
        FinanceAgingBucket: {
            /**
             * @example < 7 gün
             * @example 7-30 gün
             * @example 30+ gün
             */
            label: string;
            count: number;
            amount: number;
        };
        HealthResponse: {
            /** @example true */
            ok: boolean;
            /** @example 0.1.0-mvp */
            version: string;
            /**
             * @description Seconds since process start (3 d.p.)
             * @example 123.456
             */
            uptime: number;
        };
        CustomerCreateInput: {
            /** @example Mehmet Demir */
            name: string;
            segment: components["schemas"]["CustomerSegment"];
            stage: components["schemas"]["CustomerStage"];
            /**
             * @description Estimated lifetime value (TL)
             * @example 4500000
             */
            value: number;
            /** @enum {string} */
            source: "Sahibinden" | "Hürriyet Emlak" | "Referans" | "Sosyal Medya" | "Walk-in";
            /** @example Ayşe Yılmaz */
            owner: string;
            /** @example Çeşme tarla */
            interestArea: string;
            /**
             * Format: date-time
             * @description Optional ISO-8601 timestamp of the most recent touchpoint. When
             *     absent the API stamps `new Date().toISOString()` at create-time.
             */
            lastContact?: string;
            notes?: string | null;
        };
        /**
         * @description All properties optional — only fields present in the body are
         *     applied. The API auto-refreshes `lastContact` to `now` on every
         *     successful PATCH (see apps/api/src/routes/customers.ts).
         */
        CustomerPatchInput: {
            name?: string;
            segment?: components["schemas"]["CustomerSegment"];
            stage?: components["schemas"]["CustomerStage"];
            value?: number;
            owner?: string;
            interestArea?: string;
            notes?: string | null;
        };
        /** @description Counts per ListingStatus (post-mutation in-memory view). */
        ListingStatusCounts: {
            /** @example 42 */
            Aktif: number;
            /** @example 7 */
            Pasif: number;
            /** @example 3 */
            Taslak: number;
        };
        /** @description Counts per CustomerSegment (post-mutation in-memory view). */
        CustomerSegmentCounts: {
            /** @example 12 */
            "S\u0131cak": number;
            /** @example 25 */
            "Il\u0131k": number;
            /** @example 38 */
            "So\u011Fuk": number;
        };
        /**
         * @description RFC 6585 §4 + RFC 7231 §7.1.3 — the four headers emitted by the
         *     rate-limit middleware. `Retry-After` is only present on 429
         *     responses; the other three appear on every limited response.
         */
        RateLimitHeaders: {
            /**
             * @description Max requests per window (60 for /api/v1/*, 10 for /auth/login).
             * @example 60
             */
            "X-RateLimit-Limit"?: number;
            /**
             * @description Tokens left in the current window for this client bucket.
             * @example 59
             */
            "X-RateLimit-Remaining"?: number;
            /**
             * @description Unix-seconds at which the bucket fully refills.
             * @example 1715520060
             */
            "X-RateLimit-Reset"?: number;
            /**
             * @description Seconds to wait before retrying (429 responses only).
             * @example 42
             */
            "Retry-After"?: number;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Permission denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PageSize: number;
        /** @description Opaque cursor for pagination */
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description RFC 6585 §4 — maximum number of requests allowed in the current
         *     window. Window is 60s for `/api/v1/*` (max 60) and 60s for
         *     `/api/v1/auth/login` (max 10, brute-force defense).
         */
        XRateLimitLimit: number;
        /**
         * @description RFC 6585 §4 — tokens remaining in the current window for this client
         *     bucket. Resets to `X-RateLimit-Limit` once `X-RateLimit-Reset`
         *     elapses.
         */
        XRateLimitRemaining: number;
        /**
         * @description RFC 6585 §4 — unix-seconds timestamp at which the current bucket
         *     fully refills. Computed as ceil((lastRefill + windowMs) / 1000) by
         *     apps/api/src/lib/rate-limit.ts.
         */
        XRateLimitReset: number;
        /**
         * @description RFC 7231 §7.1.3 — seconds the client should wait before retrying.
         *     Only emitted on the 429 response.
         */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listListings: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                status?: components["schemas"]["ListingStatus"];
                type?: components["schemas"]["ListingType"];
                q?: string;
                city?: string;
                district?: string;
                priceMin?: number;
                priceMax?: number;
                areaMin?: number;
                sort?: "lastUpdate" | "price-asc" | "price-desc" | "size-desc" | "views";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Listing"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Listing"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Listing"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingPatchInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Listing"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                segment?: components["schemas"]["CustomerSegment"];
                stage?: components["schemas"]["CustomerStage"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Customer"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreateInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Customer"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Customer"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPatchInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Customer"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDeals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Deal"][];
                    };
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    moveDealStage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    toStage: components["schemas"]["CustomerStage"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Deal"];
                    };
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description OK — issues a JWT bearer with embedded `jti` (Wave-19 / A91). */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthLoginResponse"];
                    };
                };
            };
            /** @description Missing email or password (envelope INVALID_INPUT) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid credentials (envelope UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPublicOffices: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Office"][];
                    };
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPublicOffice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Office"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPublicRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Region"][];
                    };
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTenants: {
        parameters: {
            query?: {
                plan?: "Free" | "Pro" | "Enterprise";
                status?: "Aktif" | "Trial" | "Askıda" | "Churned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Tenant"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAuditEntries: {
        parameters: {
            query?: {
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                actor?: string;
                tenantId?: string;
                action?: string;
                outcome?: "success" | "failure";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditEntry"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCalendarEvents: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                type?: components["schemas"]["CalendarEventType"];
                from?: string;
                to?: string;
                owner?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CalendarEvent"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CalendarEvent"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                channel?: components["schemas"]["MessageChannel"];
                segment?: components["schemas"]["CustomerSegment"];
                unreadOnly?: boolean;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConversationSummary"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Conversation"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReportsTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TeamRow"][];
                        meta: components["schemas"]["ListMeta"] & {
                            totals?: {
                                closed: number;
                                active: number;
                                revenue: number;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReportsMonthlyClose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MonthlyClose"][];
                        meta: components["schemas"]["ListMeta"] & {
                            revenue?: number;
                            count?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReportsCustomerSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SourceRow"][];
                        meta: components["schemas"]["ListMeta"] & {
                            totalLeads?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — issues a new JWT (new jti, refreshed iat/exp). */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthRefreshResponse"];
                    };
                };
            };
            /**
             * @description Refresh denied. `error.details.reason` is one of:
             *     - `expired` — token's exp is in the past
             *     - `bad-signature` — signature did not verify
             *     - `revoked` — token's jti is in the revocation set
             *     - `too-early` — token still has >5min of life
             *     - `iat-window-elapsed` — token issued >24h ago
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listFinanceTransactions: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSize"];
                /** @description Opaque cursor for pagination */
                cursor?: components["parameters"]["Cursor"];
                from?: string;
                to?: string;
                kind?: components["schemas"]["FinanceTransactionKind"];
                status?: components["schemas"]["FinanceTransactionStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinanceTransaction"][];
                        meta: components["schemas"]["ListMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFinanceCashflow: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinanceCashflowPoint"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFinanceKpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinanceKPI"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFinancePendingByAge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinanceAgingBucket"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getListingStatusCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ListingStatusCounts"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCustomerSegmentCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CustomerSegmentCounts"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Rate limit exceeded — RFC 6585 §4 token bucket. */
            429: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["XRateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["XRateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["XRateLimitReset"];
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
